functions:
  "fetch source" :
    - command: git.get_project
      params:
        directory: src

  "build tool" :
    command: shell.exec
    params:
      directory: src
      script: |
        echo "Building ${tool}..."
        . ./set_gopath.sh
        go build ${args} -o bin/${tool} cmd/${tool}/main.go
pre:

post:

tasks:
- name: build
  commands:
  - func: "fetch source"
  - func: "build tool"
    vars:
      tool: mongoplay
  - func: "build tool"
    vars:
      tool: mongorecord


buildvariants:
- name: ubuntu
  display_name: Ubuntu
  run_on:
  - ubuntu1404-test
  tasks:
  - name: build
